targets:
  $default:
    builders:
      json_serializable:
        options:
          disallow_unrecognized_keys: true
          explicit_to_json: true
          include_if_null: true
          create_to_json: true